<?php
$lookupGun = [
       "knife"=>"KINFE",
       "glock18"=>"Glock18",
       "usp"=>" USP .45",
       "p228"=>"SIG P228",
       "deagle"=>"Desert Eagle",
       "fn57"=>"FN Five-Seven",
       "elites"=>"Dual Beretta",
       "m3"=>"Benelli M3",
       "xm1014" => "Benelli XM1014",
       "tmp"=>"Tactical Machine",
       "mac10"=>"Ingram MAC-10",
       "mp5navy"=>"MP5-Navy",
       "ump45"=>" UMP45",
       "p90"=>"FN P90",
       "galil"=>"IMI Galil",
       "famas"=>"FAMAS",
       "ak47"=>"AK-47",
       "m4a1"=>"M4a1",
       "sg552"=>"Sig SG-552",
       "aug"=>"Steyr Aug",
       "scout"=>"Steyr Scout",
       "sg550"=>"Sig SG-550",
       "awp"=>"Magnum",
       "g3sg1"=>"G3SG1",
       "m249"=>"M249",
       "grenade"=>"Grenade"
        ];
        $listTitle = ["Silver I", "Silver II", "Silver III", "Silver IV", "Silver Elite", "Silver Elite Master", "Gold Nova I", "Gold Nova II", "Gold Nova III", "Gold Nova Master", "Master Guardian I", "Master Guardian II", "Master Guardian Elite", "Distinguished Master Guardian", "Legendary Eagle", "Legendary Eagle Master", "Supreme Master First Class", "The Global Elite", ];
        $lookupEXP = [0,20,60,120,200,300,420,560,720,900,1100,1320,1560,1820,2100,2400,2720,3060]; // generated by rankingSample()  wwith step   = 7

function translateGun ($name) {
    echo ($name);
    switch ($name){
    case    "knife": return "KINFE";
    case    "glock": return"Glock18";
    case    "usp": return " USP .45";
    case    "p228": return "SIG P228";
    case    "deagle": return "Desert Eagle";
    case    "fn57": return "FN Five-Seven";
    case    "elites": return "Dual Beretta";
    case    "m3": return "Benelli M3";
    case    "xm1014": return "Benelli XM1014";
    case    "tmp": return "Tactical Machine";
    case    "mac10": return "Ingram MAC-10";
    case    "mp5": return "MP5-Navy";
    case    "ump45": return " UMP45";
    case    "p90": return "FN P90";
    case    "galil": return "IMI Galil";
    case    "famas": return "FAMAS";
    case    "ak47": return "AK-47";
    case    "m4a1": return "M4a1";
    case    "sg552": return "Sig SG-552";
    case    "aug": return "Steyr Aug";
    case    "scout": return "Steyr Scout";
    case    "sg550": return "Sig SG-550";
    case    "awp": return "AWP Magnum";
    case    "g3sg1": return "G3SG1";
    case    "m249": return "M249 ";
    }

    }
?>